management:
  endpoints:
    web:
      exposure:
        include: '*'


eureka:
  instance:
    hostname: eureka-server-app
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone : http://eureka-server-app:8761/eureka/


spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://database-app:3307/customer_app}
    username: ${SPRING_DATASOURCE_USER:root}
    password: ${SPRING_DATASOURCE_PASSWORD:leghacy150991}
    driver-class-name: com.mysql.cj.jdbc.Driver

    tomcat:
      max-wait: 200000
      max-active: 50
      max-idle: 20
      min-idle: 15
    jpa:
      show-sql: false
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5InnoDBDialect
          format_sql: true
          id:
            new_generator_mappings: true



security:
  jwt:
    token:
      secret-key: ${SECURITY_SECRET_KEY:secret-key}
      expire-length: ${TOKEN_EXPIRE:2592000000} # 30 dias

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic