management:
  endpoints:
    web:
      exposure:
        include: '*'


eureka:
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone : http://eureka-server-app:8761/eureka/


spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://database-app:3307/customer_app
    username: ${SPRING_DATASOURCE_USER:root}
    password: ${SPRING_DATASOURCE_PASSWORD:leghacy150991}


  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect




security:
  jwt:
    token:
      secret-key: ${SECURITY_SECRET_KEY:secret-key}
      expire-length: ${TOKEN_EXPIRE:2592000000} # 30 dias

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic