management:
  endpoints:
    web:
      exposure:
        include: '*'


eureka:
  instance:
    hostname: localhost
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone : http://eureka-server-app:8761/eureka/






security:
  jwt:
    token:
      secret-key: ${SECURITY_SECRET_KEY:secret-key}
      expire-length: ${TOKEN_EXPIRE:2592000000} # 30 dias

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic