

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://database-app:3307/customer_app}
    username: ${SPRING_DATASOURCE_USER:root}
    password: ${SPRING_DATASOURCE_PASSWORD:leghacy150991}
    tomcat:
      max-wait: 200000
      max-active: 50
      max-idle: 20
      min-idle: 15
    jpa:
      show-sql: false
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5InnoDBDialect
          format_sql: true
          id:
            new_generator_mappings: true

mail:
  token: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiZjYxNWMzMjkwMTQ2ZTJhOGE4Yjk5OTg1ZmM5OTkxZTEzNWJkMDI2ZjEwYWExY2QzMGU4ZWRlODg1NTQyYzI2MDBlZjliODcwYTBjYzlhYzAiLCJpYXQiOjE2NTQ2MjY2OTYuODIzNDY1LCJuYmYiOjE2NTQ2MjY2OTYuODIzNDcsImV4cCI6NDgxMDMwMDI5Ni44MTk1MTMsInN1YiI6IjI4NTI1Iiwic2NvcGVzIjpbImVtYWlsX2Z1bGwiXX0.k51A6g2c3zMbRTSMoAZ6gZIsvonBbFcpDWhCM8IDGn6d-6LVdthxdQNmaAsBmn_h4ApvS71YTHRB5wgFt_ydPJUsfdCQiAuqdEaZ4DuR2XLHCC1qbE2-R3oGfgklBHINw7tzWTlsDMTJyHpUCYq067u5SUYi2pemKt05_zKVY46QmaX51vn9rjYtDnHKI-7gEy1mrhF5RN_-LzwYynrgXKt5sXWbFcbcq51Pdq1WeXDktb94OPtQYpLWgU-PsSAInXIxyvlzVytqYpgz56vga_1d7vHvrlN1bp0mz8b-l66yTICW689q1kz3y5ESGnRabMwWCYlP_Yvy4qBK-j8HL9sd8DnKoR9JvyK4U6vgBN2kzGtqrSuWPcl3u8oXSNDZB-XsbuURCVkpdEVOJiV3MVpwTvP3a-pS56GmFehza0nJn_Xo42l5Mmeexqs_p4ZhBBzv9Gcolz35T6ZCNuh1ec34TFbW2svZnEdMbp8EVMystqSOupv-uJkP_Bu_IJVciOdp02YeK3CStT6yD25YsPxRqcvek-7O4LQPsBACUXl-sOpGxgkE8jXv51y4yhhR6NNgSHYLgbU6116VLgnHtEJQtA_5xTJnHFF19fmgDgf-FHWOC1nRcVOyjIkXqSV0uvOY4ud0UfsQRbXQOnF6hT1W7xb6oYbsS0IZFpFdcrQ